/**
 * The playground's guard around the Oxabl WebAssembly artifact.
 *
 * The engine is Rust compiled to `wasm32-unknown-unknown`, where stable Rust
 * builds with `-Cpanic=abort`. A Rust panic there does not unwind and cannot be
 * caught inside wasm: it lowers to an `unreachable` trap that reaches JS as a
 * `WebAssembly.RuntimeError`. Before this module existed, the component caught
 * that error and showed the raw string `unreachable executed` next to a green
 * status dot, above stale diagnostics from the last good run — and because the
 * module singleton cached the dead instance and the glue's `init()`
 * early-returns on an already-initialized module, every later click hit the same
 * trapped instance and showed the same message until the visitor reloaded.
 *
 * So the recovery has two halves, and they live in different repos:
 *
 * 1. **In the artifact:** a Rust panic hook stashes the formatted panic message
 *    on `globalThis.__oxablPanicMessage` before the abort. std runs the hook to
 *    completion before the panic runtime aborts, so that write lands before the
 *    trap by program order.
 * 2. **Here:** the `catch` reads that stash and calls the artifact's
 *    `__wbg_reset_state()`, which builds a fresh `WebAssembly.Instance` from the
 *    already-compiled module with Rust statics reset and re-runs the start
 *    function — which is what re-arms the panic hook for the next crash.
 *
 * This module deliberately lives in `src/lib/` rather than in the component:
 * `react-refresh/only-export-components` is an error with an allowlist of
 * exactly `["buttonVariants"]`, so a non-component export in `TryOxabl.tsx`
 * fails lint. It must not live in `src/wasm/` either — that whole directory is
 * generated output, overwritten wholesale by the oxabl repo's
 * `scripts/build-wasm.sh`, with no CI check to catch a lost hand-edit.
 *
 * What this does **not** cover: a hang. An infinite loop in the parser freezes
 * the main thread, is indistinguishable from a trap to a visitor, and needs a
 * Web Worker with a timeout.
 */

import * as glue from "@/wasm/oxabl_wasm.js"

export type Diagnostic = {
  source: "parse" | "preproc" | "semantic" | "lint"
  severity: "error" | "warning" | "info" | "hint"
  code: string
  message: string
  start: Position
  end: Position
  help: string | null
}

export type Position = {
  byte: number
  line: number
  column: number
}

export type AnalyzeResponse = {
  diagnostics: Diagnostic[]
}

export type FormatResponse = {
  source: string
  changed: boolean
  error: string | null
}

/**
 * The artifact's surface, hand-written because the build passes
 * `--no-typescript` and the glue therefore ships no `.d.ts` — its only types are
 * JSDoc. A namespace import plus this shape is also what makes the
 * stale-artifact check below possible: naming `__wbg_reset_state` and `version`
 * as static named imports from a module that lacks them is a build-time error in
 * strict ESM, whereas a namespace lets us *test* for them and report honestly.
 */
type OxablGlue = {
  default: (init?: unknown) => Promise<unknown>
  analyze_source: (source: string) => string
  format_source: (source: string) => string
  /** Added alongside the recovery path; absent from an older vendored copy. */
  version?: () => string
  /**
   * Generated by `wasm-bindgen --experimental-reset-state-function`. Absent if
   * the artifact was built without that flag — which is exactly the silent
   * failure the oxabl repo's build script asserts against, and which this module
   * detects at load as a second line of defense.
   */
  __wbg_reset_state?: () => void
}

const oxabl = glue as unknown as OxablGlue

/** The `globalThis` key the artifact's panic hook writes to. Cross-repo contract. */
const PANIC_STASH_KEY = "__oxablPanicMessage"

/** How a call failed, and — critically — whether retrying can ever help. */
export type OxablFailure =
  /**
   * A Rust panic trapped the module. **Recoverable:** the instance has already
   * been replaced by the time this is returned, so the next call runs against a
   * fresh one. The failed call itself is lost — its staged state went with the
   * old instance — so the caller re-issues nothing automatically.
   */
  | { kind: "crash"; message: string; version: string }
  /**
   * The engine cannot compile or instantiate the module at all. **Terminal:** no
   * reload-free path can succeed here, so the caller disables its controls
   * permanently rather than only while busy.
   */
  | { kind: "unsupported"; message: string }
  /**
   * The module loaded but lacks the recovery exports, meaning a stale
   * hand-vendored `src/wasm/`. **Terminal**, and reported as its own state:
   * presenting a confident crash UI over glue that cannot heal would be the very
   * defect this module exists to remove, wearing a new label.
   */
  | { kind: "stale-artifact"; message: string }
  /**
   * Fetching or starting the artifact failed in a way that may be transient — a
   * flaky network on an 828 KB download. **Retryable:** the cached promise is
   * dropped so the next attempt refetches.
   */
  | { kind: "load"; message: string }

export type OxablResult<T> =
  | { ok: true; value: T }
  | { ok: false; failure: OxablFailure }

/** Terminal failures leave the playground unusable until a page reload. */
export function isTerminal(failure: OxablFailure): boolean {
  return failure.kind === "unsupported" || failure.kind === "stale-artifact"
}

/**
 * The load promise. Cached so the 828 KB artifact downloads once — but **cleared
 * on rejection**, unlike before: a rejected promise cached forever made a single
 * flaky fetch as permanent as a panic, with a page reload the only way out.
 */
let loadPromise: Promise<OxablGlue> | undefined

/** Cheap, cached version string for crash reports. */
let cachedVersion: string | undefined

function load(): Promise<OxablGlue> {
  if (!loadPromise) {
    loadPromise = oxabl
      .default()
      .then(() => {
        // Second line of defense against a stale hand-vendored artifact. The
        // two repos have no enforced lockstep: `src/wasm/` is copied in by a
        // human running the oxabl repo's build script, and neither repo's CI
        // checks the result. Deploying this guard against older glue would
        // produce a crash state that reports an undefined version and never
        // heals.
        if (typeof oxabl.__wbg_reset_state !== "function") {
          throw new StaleArtifactError(
            "the bundled engine has no __wbg_reset_state export, so it cannot recover from a crash"
          )
        }
        if (typeof oxabl.version !== "function") {
          throw new StaleArtifactError(
            "the bundled engine has no version export, so a crash cannot be traced to a build"
          )
        }
        return oxabl
      })
      .catch((error: unknown) => {
        // Drop the cache so a transient failure is retryable. A deterministic
        // failure (unsupported engine, stale artifact) simply fails the same way
        // on the next attempt and routes to its own terminal state — retrying
        // costs one classification, not an infinite loop.
        loadPromise = undefined
        throw error
      })
  }
  return loadPromise
}

/** A stale vendored artifact — distinct from an engine that cannot run wasm. */
class StaleArtifactError extends Error {
  constructor(message: string) {
    super(message)
    this.name = "StaleArtifactError"
  }
}

function artifactVersion(): string {
  if (cachedVersion === undefined) {
    try {
      cachedVersion = oxabl.version?.() ?? "unknown"
    } catch {
      cachedVersion = "unknown"
    }
  }
  return cachedVersion
}

/**
 * Clear the panic stash before every call, and read it only afterwards.
 *
 * Without the clear, a visitor could be shown the *previous* crash's message as
 * the cause of the current one — the same stale-data-as-current defect this
 * module removes from the diagnostics panel, relocated to the status line.
 */
function clearPanicStash(): void {
  try {
    delete (globalThis as Record<string, unknown>)[PANIC_STASH_KEY]
  } catch {
    // A non-configurable property is not worth failing the call over; the read
    // below simply falls back to the no-message form.
  }
}

function readPanicStash(): string | undefined {
  const stashed = (globalThis as Record<string, unknown>)[PANIC_STASH_KEY]
  return typeof stashed === "string" && stashed.length > 0 ? stashed : undefined
}

/**
 * Classify a thrown value, and heal the instance when healing is what's called
 * for.
 *
 * Routing is by error *type*, not by string matching, which is brittle across
 * engines: a compile or link failure arrives as `WebAssembly.CompileError` /
 * `LinkError`, while a panic trap arrives as `WebAssembly.RuntimeError`.
 */
function classify(error: unknown): OxablFailure {
  if (error instanceof StaleArtifactError) {
    return { kind: "stale-artifact", message: error.message }
  }

  if (
    error instanceof WebAssembly.CompileError ||
    error instanceof WebAssembly.LinkError
  ) {
    return {
      kind: "unsupported",
      message:
        "This browser can't run the Oxabl engine. It needs a WebAssembly runtime a little newer than this one — the CLI and editor extension have no such requirement.",
    }
  }

  if (error instanceof WebAssembly.RuntimeError) {
    const stashed = readPanicStash()
    // Reset *before* the caller renders, so the engine is already healed by the
    // time the visitor can click again.
    const healed = resetInstance()
    const version = artifactVersion()
    if (!healed) {
      return {
        kind: "stale-artifact",
        message:
          "The Oxabl engine hit an internal error and this build cannot restart itself. Reload the page to continue.",
      }
    }
    return {
      kind: "crash",
      version,
      // A `RuntimeError` can also come from a non-panic trap — an engine stack
      // overflow or OOM — where the hook never ran and nothing was stashed.
      // Render a fixed fallback for that, never a previous crash's text.
      message:
        stashed ??
        "The Oxabl engine hit an internal error with no captured message (a stack overflow or out-of-memory trap, rather than a Rust panic).",
    }
  }

  return {
    kind: "load",
    message:
      error instanceof Error
        ? error.message
        : "The Oxabl engine failed to load. Check your connection and try again.",
  }
}

/**
 * Swap in a fresh instance. Returns whether it worked, so a stale artifact
 * without the export is reported as such rather than as a recoverable crash.
 */
function resetInstance(): boolean {
  const reset = oxabl.__wbg_reset_state
  if (typeof reset !== "function") return false
  try {
    reset()
    cachedVersion = undefined
    return true
  } catch {
    return false
  }
}

async function run<T>(call: (glue: OxablGlue) => T): Promise<OxablResult<T>> {
  try {
    const loaded = await load()
    clearPanicStash()
    return { ok: true, value: call(loaded) }
  } catch (error) {
    return { ok: false, failure: classify(error) }
  }
}

function parse<T>(json: string): T {
  return JSON.parse(json) as T
}

/** Analyze `source`, or report how the engine failed. */
export function analyze(source: string): Promise<OxablResult<AnalyzeResponse>> {
  return run((g) => parse<AnalyzeResponse>(g.analyze_source(source)))
}

/**
 * Format `source`, or report how the engine failed.
 *
 * Note the two error channels are different things. A **bail** — the formatter
 * declining to rewrite input it cannot reproduce faithfully — is a successful
 * call whose `FormatResponse.error` is set and whose `source` is the untouched
 * input. Only a crash is an `ok: false`.
 */
export function format(source: string): Promise<OxablResult<FormatResponse>> {
  return run((g) => parse<FormatResponse>(g.format_source(source)))
}

/** The artifact identifier, for display. `"unknown"` before the engine loads. */
export function engineVersion(): string {
  return artifactVersion()
}

/**
 * A pre-filled issue URL for a crash, built entirely client-side — no telemetry
 * and no automatic reporting.
 *
 * This exists because nothing today would tell the team whether the engine's
 * panic surface is ever reached by real ABL. All five parser `unreachable!()`
 * sites are caller-guarded, so a crash report from a visitor's actual source is
 * genuinely new information, and without it the deferred parser-hardening work
 * stays unprioritizable indefinitely.
 */
export function crashReportUrl(
  failure: Extract<OxablFailure, { kind: "crash" }>,
  source: string
): string {
  const body = [
    "The browser playground hit an internal error.",
    "",
    `**Engine build:** \`${failure.version}\``,
    "",
    "**Message**",
    "",
    "```",
    failure.message,
    "```",
    "",
    "**Source that triggered it**",
    "",
    "```abl",
    source,
    "```",
  ].join("\n")

  const params = new URLSearchParams({
    title: "Playground: internal error on this input",
    body,
    labels: "bug,playground",
  })
  return `https://github.com/oxabl-project/oxabl/issues/new?${params.toString()}`
}
